# Initiation à Python et Numpy

## a) Import de Numpy

In [2]:
import numpy as np
print(np.__version__)

1.19.2


## Création d'un tableau à une dimension

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Création d'un tableau à 2 dimensions

In [9]:
print(np.ones((3,3)))
print("++++")
print(np.zeros((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
++++
[[0. 0. 0.]
 [0. 0. 0.]]


## Création d'un tableau de booléens à 2 dimensions

In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Question 1 : 
Créer automatiquement un tableau contenant 10 fois le chiffre 0, un autre contenant 10 fois le chiffre 1 et un dernier contenant 10 fois le chiffre 5. Le résultat attendu est présenté ci-dessous. Vous devez compléter la cellule.

In [12]:

print("Premier tableau:")

print("Deuxième tableau:")

print("Troisième tableau:")


Premier tableau:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Deuxième tableau:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Troisième tableau:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Extraire les chiffres impairs d'un tableau

In [10]:
# entrée
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## Question 2:
Écrire un code qui permet d'extraire  les chiffres pairs d'un tableau de votre choix.

## Question 3:
1. Écrire un code qui permet de mettre à jour la 6ieme valeur à 11 d'un tableau contenant 10 fois le chiffre 0. 
2. Écrire un code qui permet de remplacer tous les chiffres impairs dans un tableau par le chiffre -1.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Mis à jour de la 6irmr valeur à 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
++++
Tableau initial : [0 1 2 3 4 5 6 7 8 9] 
Tableau final : [ 0 -1  2 -1  4 -1  6 -1  8 -1] 


## Remplacer tous les chiffres impairs dans un tableau par le chiffre -1 sans modifier le tableau initial.

In [16]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Redomensionner un tableau

In [20]:
arr = np.arange(10)
print(arr)
print(arr.reshape(2, -1))  # mettre -1 permet de décider automatiquement du nombre de colonnes

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question 4:
1. Écrire un code qui permet de redimensionner un tableau contenant 10 chiffres en un tableau à 2 dimensions. Le tableau doit avoir 2 colonnes.
2. Écrire un code qui permet de créer un tableau 3D (3x3) avec des valeurs allant de 2 à 10.

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
++++
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Concatener des tableaux horizontallement

In [30]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print("Tableau a :")
print(a)
print("Tableau b :")
print(b)

# Methode 1:
print("Méthode 1: ")
print(np.concatenate([a, b], axis=1))

# Methode 2:
print("Méthode 2:")
print( np.hstack([a, b]))

# Methode 3:
print("Méthode 3: ")
print( np.c_[a, b])

Tableau a :
[[0 1 2 3 4]
 [5 6 7 8 9]]
Tableau b :
[[1 1 1 1 1]
 [1 1 1 1 1]]
Méthode 1: 
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Méthode 2:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Méthode 3: 
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question 5:
Concatener les deux tableaux a et b ci-dessus vertivalement avec la méthode 1.

## Obtenir les positions des éléments similaires entre 2 tableaux

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

## Question 6:
Comment obtenir les positions où la sommes des éléments est égale à 10 ? Par exemple pour les 2 tableaux ci-dessus la solution est **4** puisque à la position 4 du tableau a on a **3** et à la position 4 du tableau b on a **7**. Puis **3 + 7 = 10**. 

In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

(array([4]),)

## Question 7:
Comment extraire les chiffres compris entre 5 et 9 dans le tableau ***a = np.array([7,2,10,2,7,4,9,4,9,8])***. La solution attendue est prédenté ci-dessous 

array([7, 7, 9, 9, 8])

## Échanger deux colonnes dans un tableau numpy 2D?

In [37]:
# Entrée
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## Question 8:
Comment échanger deux lignes dans un tableau 2D ? 

## Question 9
Analyser le code suivant. Il s'agit de comprendre comment fonctionne l'indexage avec numpy. Vous pouvez modifier le code à votre guise.

In [42]:
a = np.array([7,2,10,2,7,4,9,4,9,8])
print(a[:-1])
print(a[:-2])
print(a[:-4])
print(a[-4])
print(a[3])

[ 7  2 10  2  7  4  9  4  9]
[ 7  2 10  2  7  4  9  4]
[ 7  2 10  2  7  4]
9
2


## Question 10
Manipuler les index dans un tableau à 2 dimensions. Vous pouvez modifier le code et essayer de comprendre comment fonctionne l'indexage dans un tableau 2D et peut être 3D aussi.

In [44]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5 8]
